service:
  name: n8n-postgres
  image: ghcr.io/railwayapp-templates/postgres-ssl:16

deploy:
  startCommand: "/bin/sh -c 'unset PGPORT; docker-entrypoint.sh postgres --port=5432'"
  restartPolicyType: ON_FAILURE
  restartPolicyMaxRetries: 10

networking:
  tcpProxyPort: 5432

volume:
  mountPath: /var/lib/postgresql/data

variables:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "$env(N8N_POSTGRES_PASSWORD)"
  POSTGRES_DB: "n8n"
  PGUSER: "${{n8n-postgres.POSTGRES_USER}}"
  PGPASSWORD: "${{n8n-postgres.POSTGRES_PASSWORD}}"
  PGDATABASE: "${{n8n-postgres.POSTGRES_DB}}"
  PGHOST: "${{RAILWAY_PRIVATE_DOMAIN}}"
  PGPORT: "5432"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  DATABASE_URL: "postgresql://${{n8n-postgres.POSTGRES_USER}}:${{n8n-postgres.POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:5432/${{n8n-postgres.POSTGRES_DB}}"
